server {
	listen 80;
	server_name www.sample.com;
	location / {

		root /usr/share/nginx/html/;
		index index.html;
	}	
	location ~ \.php$ {

	   include fastcgi_params;
	    fastcgi_pass back-php:9000;
	    fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
	}


}
